"""Regression test generator: turn a failed trace into executable pytest code.

The generated file is self-contained: the trace rides along as base64, so the
test can be committed to the user's repo and guarded by CI without access to
the Approximately store.

Two kinds of guard are emitted:

1. *Replay guard* — replay the recorded steps through the user's executor and
   require step-level agreement, so behavioral drift fails CI.
2. *Contract guards* — per-failure-mode assertions over a fresh run (the user
   wires ``<ENTRY>`` to a callable that executes their agent against a fresh
   Recorder). Example: after FM-1.3, "the same (tool, args) must not be called
   twice"; after FM-3.2, "every mutating call must be followed by a verify".
"""

from __future__ import annotations

import base64
import json
from typing import List

from .attributor import FailureReport
from .trace import TOOL_CALL, Trace

HEADER = '''"""Regression guards for agent trace {trace_id} — generated by Approximately.

Regenerate with: approximately test {trace_id}

The trace is embedded below; the replay guard needs an executor that can
perform the recorded steps. Wire AGENT_ENTRY to a callable that runs your
agent against a fresh approximately Recorder to enable contract guards.
"""

import base64
import json

import pytest

from approximately import Recorder, attribute, replay

TRACE_B64 = (
{trace_b64}
)

AGENT_ENTRY = None  # e.g. "myapp.agent:run" — callable(Recorder) -> None


def _trace():
    from approximately.trace import Trace

    return Trace.from_dict(json.loads(base64.b64decode(TRACE_B64)))
'''


def _guards_for(report: FailureReport) -> List[str]:
    guards: List[str] = []
    modes = {d.mode_id for d in report.detections}
    if "FM-1.3" in modes:
        guards.append(
            '''
def test_no_repeated_tool_calls():
    """FM-1.3 regression: identical (tool, args) must not be called twice."""
    recorded, seen = _trace(), set()
    repeats = []
    for step in recorded.steps:
        if step.kind != "tool_call" or step.error:
            continue
        fp = step.fingerprint()
        if fp in seen:
            repeats.append(step.short())
        seen.add(fp)
    assert not repeats, f"repeated tool calls: {repeats}"
'''
        )
    if "FM-3.2" in modes:
        guards.append(
            '''
def test_mutating_calls_are_verified():
    """FM-3.2 regression: every mutating call is followed by a verification."""
    trace = _trace()
    unverified = []
    for i, step in enumerate(trace.steps):
        if step.kind != "tool_call" or not step.meta.get("mutating"):
            continue
        later = trace.steps[i + 1:]
        ok = any(
            s.meta.get("verify") or (s.kind == "tool_call" and s.tool and
             any(m in s.tool.lower() for m in ("verify", "check", "confirm", "get_", "status")))
            for s in later
        )
        if not ok:
            unverified.append(step.short())
    assert not unverified, f"mutating calls without verification: {unverified}"
'''
        )
    if "FM-3.1" in modes:
        guards.append(
            '''
def test_no_premature_termination():
    """FM-3.1 regression: a failed run must not end silently after an error."""
    trace = _trace()
    if trace.success is False and trace.steps:
        last = trace.steps[-1]
        assert last.kind != "error", (
            f"run still ends on an unhandled error: {last.error}"
        )
'''
        )
    if "FM-2.1" in modes:
        guards.append(
            '''
def test_no_conversation_reset():
    """FM-2.1 regression: the seed prompt must not be re-issued mid-run."""
    trace = _trace()
    seed = trace.task.strip().lower()
    for step in trace.steps[1:]:
        assert not (step.kind == "plan" and step.thought and
                    step.thought.strip().lower() == seed), (
            f"conversation reset at step #{step.index}"
        )
'''
        )
    if not guards:
        guards.append(
            '''
def test_primary_mode_is_gone():
    """Regression: the attributed failure mode must not recur.

    Wire AGENT_ENTRY and run your agent under a fresh Recorder, then require
    that Approximately no longer attributes the original failure mode.
    """
    if AGENT_ENTRY is None:
        pytest.skip("set AGENT_ENTRY to enable contract guards")
    module, _, fn = AGENT_ENTRY.partition(":")
    entry = getattr(__import__(module), fn)
    with Recorder(_trace().task, save=False) as rec:
        entry(rec)
    report = attribute(rec.trace)
    assert report.primary_mode.id != "{mode}", (
        f"failure recurred: {report.summary}"
    )
'''.replace("{mode}", report.primary_mode.id)
        )
    return guards


def render_regression(trace: Trace, report: FailureReport) -> str:
    payload = base64.b64encode(
        json.dumps(trace.to_dict(), default=str).encode("utf-8")
    ).decode("ascii")
    b64_lines = "\n".join(
        f'    "{payload[i : i + 76]}"' for i in range(0, len(payload), 76)
    )
    parts = [
        HEADER.format(trace_id=trace.id, trace_b64=b64_lines),
        f'''
def test_replay_consistency():
    """The recorded steps must still replay faithfully (threshold 0.85)."""
    diff = replay(_trace(), executor=EXECUTOR)
    assert diff.match_rate >= 0.85, diff.summary()


EXECUTOR = None  # Callable[[Step], str]; None -> replay guard skips
'''
    ]
    # Make the replay guard skip gracefully when no executor is wired.
    parts[1] = parts[1].replace(
        "def test_replay_consistency():",
        "def test_replay_consistency():",
        1,
    )
    parts[1] = parts[1].replace(
        '    diff = replay(_trace(), executor=EXECUTOR)',
        '    if EXECUTOR is None:\n'
        '        pytest.skip("set EXECUTOR to enable the replay guard")\n'
        '    diff = replay(_trace(), executor=EXECUTOR)',
    )
    parts.extend(_guards_for(report))
    return "\n".join(parts)
