"""`approximately new <name>` — scaffold a runnable, instrumented agent project.

Generates a small package with the recorder wired, one deliberate failure,
and a regression test — so the 30-second demo becomes *your* 30 seconds.
"""

from __future__ import annotations

from pathlib import Path

AGENT_TEMPLATE = '''"""A tiny booking agent instrumented with approximately.

Run:  python {name}/agent.py
"""

from pathlib import Path

from approximately import Recorder, agentstep, current_recorder


@agentstep
def search_flights(origin: str, destination: str) -> str:
    # real agent: call your LLM/tool here
    return "JT-044 $880 | KE-102 $924"


def run(task: str) -> str:
    with Recorder(task, model="my-agent") as rec:
        rec.plan("search, pick cheapest, book, verify")
        search_flights("SFO", "NRT")
        rec.tool("book_flight", {{"seat": "12A"}}, result="BOOKED #1",
                 mutating=True)
        # TODO: add a verification step here (FM-3.2 will flag its absence)
        response = "Booked seat 12A."
        rec.respond(response, success=True)
        return response


if __name__ == "__main__":
    store = Path.home() / ".approximately" / "traces"
    store.mkdir(parents=True, exist_ok=True)
    from approximately import attribute, render_html

    with Recorder("Book the cheapest SFO-NRT flight under $900") as rec:
        rec.plan("search and book")
        search_flights("SFO", "NRT")
        rec.tool("book_flight", {{"seat": "12A"}}, result="BOOKED #2",
                 mutating=True)
        rec.respond("Booked!", success=True)
    report = attribute(rec.trace)
    print(report.summary)
    out = store / f"{{rec.trace.id}}.report.html"
    out.write_text(render_html(rec.trace, report), encoding="utf-8")
    print(f"report: {{out}}")
'''

TEST_TEMPLATE = '''"""Regression guards generated from your own failures.

Run:  pytest {name}/test_agent_regressions.py
"""

from approximately import Recorder, attribute


def test_mutating_calls_are_verified():
    """FM-3.2 guard: every mutating call must be followed by a verification."""
    from approximately import Recorder

    rec = Recorder("guard run", save=False)
    # drive your agent here; assert the convention directly:
    steps = rec.trace.steps
    mutating = [s for s in steps if s.kind == "tool_call"
                and s.meta.get("mutating")]
    for i, step in enumerate(mutating):
        later = steps[step.index + 1:]
        assert any(s.kind == "tool_call" and s.tool and
                   any(m in s.tool.lower() for m in ("verify", "check", "get_"))
                   for s in later), f"unverified mutating call: {{step.tool}}"


def test_no_repeated_tool_calls():
    """FM-1.3 guard: identical (tool, args) must not be called twice."""
    rec = Recorder("guard run", save=False)
    seen, repeats = set(), []
    for step in rec.trace.steps:
        if step.kind != "tool_call" or step.error:
            continue
        fp = step.fingerprint()
        if fp in seen:
            repeats.append(step.short())
        seen.add(fp)
    assert not repeats, f"repeated tool calls: {{repeats}}"
'''

README_TEMPLATE = """# {name}

Generated by [approximately](https://github.com/B1ueMu3ic4m/approximately).

```bash
pip install approximately
python {name}/agent.py        # runs the instrumented agent, writes a report
pytest {name}/test_agent_regressions.py
```

Next steps: replace the scripted tools with your real ones — recording and
postmortems keep working unchanged.
"""


def scaffold(name: str, base: Path = Path(".")) -> Path:
    """Create ./<name>/ with an instrumented agent, guards, and a README."""
    target = base / name
    target.mkdir(parents=True, exist_ok=True)
    (target / "agent.py").write_text(
        AGENT_TEMPLATE.format(name=name), encoding="utf-8")
    (target / "test_agent_regressions.py").write_text(
        TEST_TEMPLATE.format(name=name), encoding="utf-8")
    (target / "README.md").write_text(
        README_TEMPLATE.format(name=name), encoding="utf-8")
    return target
