"""Project scaffolding.

`approximately new <name>` scaffolds a runnable, instrumented agent
project — the recorder wired, one deliberate failure, a regression
test.  `approximately init` wires the CI quality gate into an
existing repo instead: a workflow that fails the build when
recorded runs breach a ceiling, a starter price table, and a
.gitignore line so the store never lands in git.
"""

from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Any, Dict

AGENT_TEMPLATE = '''"""A tiny booking agent instrumented with approximately.

Run:  python {name}/agent.py
"""

from pathlib import Path

from approximately import Recorder, agentstep, current_recorder


@agentstep
def search_flights(origin: str, destination: str) -> str:
    # real agent: call your LLM/tool here
    return "JT-044 $880 | KE-102 $924"


def run(task: str) -> str:
    with Recorder(task, model="my-agent") as rec:
        rec.plan("search, pick cheapest, book, verify")
        search_flights("SFO", "NRT")
        rec.tool("book_flight", {{"seat": "12A"}}, result="BOOKED #1",
                 mutating=True)
        # TODO: add a verification step here (FM-3.2 will flag its absence)
        response = "Booked seat 12A."
        rec.respond(response, success=True)
        return response


if __name__ == "__main__":
    store = Path.home() / ".approximately" / "traces"
    store.mkdir(parents=True, exist_ok=True)
    from approximately import attribute, render_html

    with Recorder("Book the cheapest SFO-NRT flight under $900") as rec:
        rec.plan("search and book")
        search_flights("SFO", "NRT")
        rec.tool("book_flight", {{"seat": "12A"}}, result="BOOKED #2",
                 mutating=True)
        rec.respond("Booked!", success=True)
    report = attribute(rec.trace)
    print(report.summary)
    out = store / f"{{rec.trace.id}}.report.html"
    out.write_text(render_html(rec.trace, report), encoding="utf-8")
    print(f"report: {{out}}")
'''

TEST_TEMPLATE = '''"""Regression guards generated from your own failures.

Run:  pytest {name}/test_agent_regressions.py
"""

from approximately import Recorder, attribute


def test_mutating_calls_are_verified():
    """FM-3.2 guard: every mutating call must be followed by a verification."""
    from approximately import Recorder

    rec = Recorder("guard run", save=False)
    # drive your agent here; assert the convention directly:
    steps = rec.trace.steps
    mutating = [s for s in steps if s.kind == "tool_call"
                and s.meta.get("mutating")]
    for i, step in enumerate(mutating):
        later = steps[step.index + 1:]
        assert any(s.kind == "tool_call" and s.tool and
                   any(m in s.tool.lower() for m in ("verify", "check", "get_"))
                   for s in later), f"unverified mutating call: {{step.tool}}"


def test_no_repeated_tool_calls():
    """FM-1.3 guard: identical (tool, args) must not be called twice."""
    rec = Recorder("guard run", save=False)
    seen, repeats = set(), []
    for step in rec.trace.steps:
        if step.kind != "tool_call" or step.error:
            continue
        fp = step.fingerprint()
        if fp in seen:
            repeats.append(step.short())
        seen.add(fp)
    assert not repeats, f"repeated tool calls: {{repeats}}"
'''

README_TEMPLATE = """# {name}

Generated by [approximately](https://github.com/B1ueMu3ic4m/approximately).

```bash
pip install approximately
python {name}/agent.py        # runs the instrumented agent, writes a report
pytest {name}/test_agent_regressions.py
```

Next steps: replace the scripted tools with your real ones — recording and
postmortems keep working unchanged.
"""


_NAME_RE = re.compile(r"^[A-Za-z0-9][A-Za-z0-9_.-]*$")


def scaffold(name: str, base: Path = Path(".")) -> Path:
    """Create ./<name>/ with an instrumented agent, guards, and a README."""
    if not _NAME_RE.match(name) or ".." in name:
        raise ValueError(
            f"invalid project name {name!r}: use letters, digits, '.', '_' '-'"
        )
    target = base / name
    target.mkdir(parents=True, exist_ok=True)
    (target / "agent.py").write_text(
        AGENT_TEMPLATE.format(name=name), encoding="utf-8")
    (target / "test_agent_regressions.py").write_text(
        TEST_TEMPLATE.format(name=name), encoding="utf-8")
    (target / "README.md").write_text(
        README_TEMPLATE.format(name=name), encoding="utf-8")
    return target

# --- approximately init: gate an existing repo -----------------------

_STORE_DIR = ".agents-store"

_WORKFLOW = """\
name: agent-gate
on: [push, workflow_dispatch]
jobs:
  gate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: pip install approximately
      - name: quality-gate the recorded agent runs
        run: |
          approximately ci --store {store} \\
            --max-failure-rate 0.3 \\
            --max-p95-latency-ms 15000 \\
            --max-tokens 2000000 \\
            --max-budget-breaches 0 \\
            --min-traces 1
          # tune ceilings, then add a spend gate:
          #   approximately ci --store {store} --max-spend 5 --prices prices.json
""".format(store=_STORE_DIR)

_AUDIT_WORKFLOW = """\
name: agent-audit
on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:
jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: pip install approximately
      - name: nightly audit (doctor + gate + forecast)
        run: |
          approximately audit --store {store} \\
            --max-failure-rate 0.3 \\
            --max-p95-latency-ms 15000 \\
            --max-tokens 2000000 \\
            --max-budget-breaches 0 \\
            --min-traces 1 \\
            --grade-floor F \\
            --triage-top 5 \\
            --fix
        # add --digest-dir + --spend-ceiling once a watch feeds digests
        # raise --grade-floor from F toward B as your agents mature
""".format(store=_STORE_DIR)

_PRICES: Dict[str, Any] = {
    "gpt-4o": 2.5,
    "gpt-4o-mini": 0.15,
    "claude-sonnet-4": 1.8,
}

_GITIGNORE_LINE = f"{_STORE_DIR}/"


def init_scaffold(directory: Path, force: bool = False) -> Dict[str, Any]:
    """Wire the CI gate into *directory*; per-file status.

    ``written`` (created), ``appended`` (.gitignore line added to an
    existing file), or ``skipped`` (already there — nothing is ever
    overwritten without ``force``).  Re-running is idempotent.
    """
    directory.mkdir(parents=True, exist_ok=True)
    result: Dict[str, Any] = {}

    wf_path = directory / ".github" / "workflows" / "agent-gate.yml"
    result[str(wf_path)] = _write_once(wf_path, _WORKFLOW, force)

    audit_path = (directory / ".github" / "workflows" /
                  "agent-audit.yml")
    result[str(audit_path)] = _write_once(audit_path,
                                          _AUDIT_WORKFLOW, force)

    prices_path = directory / "prices.json"
    result[str(prices_path)] = _write_once(
        prices_path, json.dumps(_PRICES, indent=2) + "\n", force)

    gi_path = directory / ".gitignore"
    existing = ""
    if gi_path.is_file():
        try:
            existing = gi_path.read_text(encoding="utf-8")
        except OSError:
            result[str(gi_path)] = "refused"
            return result
    try:
        if _GITIGNORE_LINE in existing.splitlines():
            result[str(gi_path)] = "skipped"
        elif existing:
            pad = "" if existing.endswith("\n") else "\n"
            gi_path.write_text(existing + pad + _GITIGNORE_LINE + "\n",
                               encoding="utf-8")
            result[str(gi_path)] = "appended"
        else:
            gi_path.write_text(_GITIGNORE_LINE + "\n", encoding="utf-8")
            result[str(gi_path)] = "written"
    except OSError:
        result[str(gi_path)] = "refused"
    return result


def _write_once(path: Path, content: str, force: bool) -> str:
    if path.exists() and not force:
        return "skipped"
    try:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
    except OSError:
        # a hostile tree (a file that is a directory, a read-only
        # parent) is a refusal, not a traceback
        return "refused"
    return "written"
